version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test@123

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/sales  
    ports:
      - "8000:8000"
    depends_on:
      - db
